### ISSUE TITLE
Bug: trasnliterator fails on some packages

### ISSUE THREAD

**Issue by iliapolo** [cdklabs/construct-hub#127]
For examples, for `@aws-cdk/aws-autoscaling`:

```console
Error: Sample uses literate source test/example.images.lit.ts, but not found: /tmp/workdir6yEJu7/node_modules/@aws-cdk/aws-autoscaling/test/example.images.lit.ts
--
stack.1 | at loadLiterateSource (/var/task/index.js:130207:15)
stack.2 | at Object.fixturize (/var/task/index.js:130188:18)
stack.3 | at Object.allTypeScriptSnippets (/var/task/index.js:139895:34)
stack.4 | at allTypeScriptSnippets.next (<anonymous>)
stack.5 | at Rosetta.addAssembly (/var/task/index.js:140065:22)
stack.6 | at async loadAssemblies (/var/task/index.js:142608:9)
stack.7 | at async transliterateAssembly2 (/var/task/index.js:142579:26)
stack.8 | at async Runtime.handler (/var/task/index.js:142734:7)
```

This happens even though we do have transliterated README in the api ref docs: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/README.html

**Comment by iliapolo** [comment]
This happens because the necessary `.lit` files are not published in the npm tarball. There is nothing we can apart from allowing `jsii-rosetta` to skip over these types of failures and fallbak to the source language code.
