### ISSUE TITLE
npmjs follower sporadic failures to update marker

### ISSUE THREAD

**Issue by iliapolo** [cdklabs/construct-hub#832]
We are seeing sporadic failures in the NpmJS follower lambda:

```console
2022-04-04T18:13:22.730+03:00 | 2022-04-04T15:13:22.727Z c0f490d0-53ad-4e39-91e8-076300e46e95 INFO Updating last transaction marker to 9715667
-- | --
  | 2022-04-04T18:13:23.570+03:00Copy2022-04-04T15:13:23.570Z	c0f490d0-53ad-4e39-91e8-076300e46e95	ERROR	Uncaught Exception 	{     "errorType": "Error",     "errorMessage": "unexpected end of file",     "code": "Z_BUF_ERROR",     "errno": -5,     "stack": [         "Error: unexpected end of file",         "    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)",         "    at Zlib.callbackTrampoline (internal/async_hooks.js:130:17)"     ] } | 2022-04-04T15:13:23.570Z c0f490d0-53ad-4e39-91e8-076300e46e95 ERROR Uncaught Exception {"errorType":"Error","errorMessage":"unexpected end of file","code":"Z_BUF_ERROR","errno":-5,"stack":["Error: unexpected end of file"," at Zlib.zlibOnError [as onerror] (zlib.js:187:17)"," at Zlib.callbackTrampoline (internal/async_hooks.js:130:17)"]}
```

Seems to be happening when updating the marker file.

**Comment by iliapolo** [comment]
The PR that closed this issue didn't fix the problem. Reopening.

**Comment by iliapolo** [comment]
These errors turned out to be legit, as they are coming from our attempt to `gunzip` a truncated response from the replica, so the failure is appropriate.
